### ISSUE TITLE
Coursera course description

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/Documentation_and_Usability#80]
Hi!
This is how I have my course description -but I am open to modifying it. What do you think:

Informatics research often requires multidisciplinary teams. This requires more flexibility to communicate with team members with distinct backgrounds. Furthermore, team members often have different research and career goals. This can present unique challenges in making sure that everyone is on the same page and cohesively working together. This course aims to provide research leaders with guidance about:

How to effectively lead and support team members on informatics projects
How to perform informatics projects well
How to support informatics collaborators, mentees, and employees
How to better support diversity within your team
Tools that can help you perform informatics projects well

Target audience:

The course is intended for researchers who lead research teams or collaborate with others to perform multidisciplinary work. We have especially aimed the material for those with moderate to no computational experience who may lead or collaborate with informatics experts. However this material is also applicable to informatics experts working with others who have less computational experience.

Curriculum:

We will provide you with an awareness for the specific challenges that your informatics collaborators, employees, and mentees might face, as well as ways to mitigate these challenges. By creating a better work environment for your informatics research team, you will ultimately improve the potential impact of your work.

We will also discuss the major pitfalls of informatics research and discuss best practices for performing informatics research correctly and well, so that you can get the most out of your informatics projects.

This course is part of a series of courses for the Informatics Technology for Cancer Research (ITCR) called the Informatics Technology for Cancer Research Education Resource. This material was created by the ITCR Training Network (ITN) which is a collaborative effort of researchers around the United States to support cancer informatics and data science training through resources, technology, and events. This initiative is funded by the following grant: National Cancer Institute (NCI) UE5 CA254170. Our courses feature tools developed by ITCR Investigators and make it easier for principal investigators, scientists, and analysts to integrate cancer informatics into their workflows. Please see our website at www.itcrtraining.org for more information.

Many people also contributed to this course: https://jhudatascience.org/ITCR_Cancer_Research_Leadership/about-the-authors.html

**Comment by carriewright11** [comment]
Also note that Ira may want us to change this... He knows how courses get marketed.

**Comment by carriewright11** [comment]
Also maybe we can list other important people on the main image or somewhere else?

**Comment by carriewright11** [comment]
Comment from Ira about this from basecamp:
The course image solution will work (to an extent) on LeanPub but it won't for Coursera. Course images in Coursera are used for promotion on platform and off, but they don't actually appear on the landing page itself.
 and Jeff:
We can incorporate into the first or last lecture and the course description though...right  Ira ?
and Ira:
First or last lecture is fine. Basically, anywhere within the internal course content is fine. Course description isn't ideal because space is limited.

**Comment by cansavvy** [comment]
This seems similar (or identical to your introduction.Rmd section? I modeled mine after your description I think too. But I haven't added it to Coursera.
