### ISSUE TITLE
Suggestion of new usability content to add

### ISSUE THREAD

**Issue by maryjgoldman** [jhudsl/Documentation_and_Usability#89]
First off, this course is really great! I think usability and documentation is often overlooked by tool developers so it's great to see a course devoted to this. In particular the section on thinking about your user is so important! Just remembering that you are not the end user can help the usability of tool so much. I also really like the section on how to do user testing. So many great resources in there! 

My suggestion is to add another section, or perhaps to augment the user testing session, with an intermediate step of doing usability testing with other people in your lab, people from the hallway, other tool developers, etc. While usability testing with real users is very important, you also want to catch the main usability bugs before users see them. By doing some quick usability testing with whoever you can grab throughout the development process, or even just before release, you can catch major usability issues before anyone sees them. While I completely agree that other bioinformaticians are not the target user and hence have a different perspective, they still have used web and computer applications and often can find major issues that don't require specialized knowledge to experience them (e.g. this button is not in an intuitive place, I don't understand what these colors mean, etc).

**Comment by cansavvy** [comment]
Thanks so much for your feedback! I'm glad you mentioned this. I guess we never explicitly explaining the testing bit in the user feedback chapter. I will definitely add some more details about using internal testing! 

Thanks!
